### ISSUE TITLE
CameraControllerMod to allow scrolling past the borders of the map

### ISSUE THREAD

**Issue by javisar** [javisar/ONI-Modloader-Mods#90]
[NitroTurtle]
Is it possible to change the CameraControllerMod to allow scrolling past the borders of the map?  When zoomed out all the way, it works fine, but as soon as you zoom in it snaps back to within the map boundaries.  The camera also allows scrolling past the map boundaries when in debug mode with the debug menu open.  

I really hate how the UI gets in the way when working near the edges of the map.  Allowing the camera to scroll past the boundaries would allow the camera to be zoomed in and centered on the edge of the map making it much easier to work near the edge.  I really thought it worked like this in previous versions, so I'm not sure if maybe something changed in game or maybe I'm just remembering it wrong.  Anyways, just wondered if you had any ideas.  Thanks!

**Comment by fistak** [comment]
Hi,

I'm pretty sure @Moonkis already solved this, and [NitroTurtle] remembers this functionality from my modpack or OnionPatcher. Looks like this functionality wasn't carried over properly.

`CameraController.ConstrainToWorld` method clips to the world boundaries.

As [NitroTurtle] said the camera is not constrained to the world in debug mode, because entering debug mode changes `CameraController.FreeCameraEnabled` to true, and this is checked against in the `CameraController.ConstrainToWorld`.

One solution would be to change `CameraController.FreeCameraEnabled` value, but every time player leaves debug mode it will be overwritten, so I think it's more straightforward to just never let `CameraController.ConstrainToWorld` execute.

This leads to camera never being constrained (tip: just hit 'H' to go back to your base when you get lost in the emptiness)

Luckily adding this small snippet to `CameraControllerMod` should allow for scrolling past boundaries.

```
/// <summary>
/// Stop constraining camera to the world.
/// </summary>
[HarmonyPatch(typeof(CameraController), "ConstrainToWorld")]
public static class FreeCameraMod
{
    public static bool Prefix()
    {
        return false;
    }
}
```

Of course it would be best to create seperate mod sub-project for it, so it can be toggled at will.

**Comment by fistak** [comment]
This feature was added in #95, closing the issue.
